---
- name: Create Network Security group
  azure_rm_securitygroup:
    resource_group: "{{ resourcegroup }}"
    name: "{{ networksecuritygroup_name }}"
    purge_rules: yes
    rules:
        - name: "{{ rulename }}"
          protocol: "{{ ruleprotocol }}"
          source_address_prefix:
            - "{{ rulesourceaddress }}"
          destination_port_range: "{{ ruledestinationportrange }}"
          access: "{{ ruleaccess }}"
          priority: "{{ rulepriority }}"
          direction: "{{ ruledirection }}"
    tags:
        project: "tag_project"
        owner: "tag_owner"